language: cpp
compiler: g++

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
    - libgtest-dev

after_install:
- "cd /usr/src/gtest && sudo cmake . && sudo cmake --build . && sudo mv libg* /usr/local/lib/ ; cd -"
- export CXX="g++-4.9"

script: scons && scons tests && build/tests/omtest

