import os

env = Environment(CCFLAGS = "-std=c++11 -g -Wall -Werror ",
        CPPDEFINES=['__GXX_EXPERIMENTAL_CXX0X__'],
        CPPPATH = "../../src", LIBPATH = "../../build")

Import("lib_util")

# Load environment variables
env.Replace(**os.environ)

# Source section
util_sources = Split("""
util/log/LoggerTests.cpp
""")

# Object section
omtest = env.Program("omtest",
        source = [
            util_sources,
            "Main.cpp"
        ],
        LIBS = [lib_util, "gtest"]);

# Target section
# ...
all_targets = [omtest]

# Aliases
env.Alias("tests", all_targets)

