import os

env = Environment(CCFLAGS = "-std=c++11 -g -Wall -Werror",
        CPPDEFINES=['__GXX_EXPERIMENTAL_CXX0X__'],
        CPPPATH = ["."],
        LIBPATH = [])

# Load environment variables
env.Replace(**os.environ)

# Source section
util_sources = Split("""
om/util/log/Logger.cpp
om/util/log/LogConfig.cpp
""")


# Object section
util_objects = env.Object(source = util_sources)

# Target section
lib_util = env.Library(
        target = 'om-util',
        source = util_objects)

all_targets = [lib_util]


# Aliases
env.Alias("all", all_targets)

Default(all_targets)


# Export libraries for tests
Export("lib_util");

