import os

env = Environment(CCFLAGS = "-std=c++11 -g",
        CPPDEFINES=['__GXX_EXPERIMENTAL_CXX0X__'],
        CPPPATH = [".", "../depend/dawn/src"],
        LIBPATH = ["../depend/dawn/build"])

# Load environment variables
env.Replace(**os.environ)

# Source section
common_sources = Split("""
""")

login_sources = Split("""
login/Main.cpp
""")


# Object section
common_objects = env.Object(source = common_sources)
login_objects = env.Object(source = login_sources)

# Target section
login_server = env.Program(
        target = 'login-server',
        source = login_objects,
        LIBS = ['dawn-log'])
all_targets = [login_server]


# Aliases
env.Alias("all", all_targets)

Default(all_targets)

